# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.2 (rev. 214)

EAPI=3

# Warning: Invalid LICENSE.
inherit distutils

MY_PN="keyring"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="Store and access your passwords safely."
HOMEPAGE="http://home.python-keyring.org/"
SRC_URI="http://pypi.python.org/packages/source/k/keyring/${MY_P}.zip"
LICENSE="PSF"
KEYWORDS="~amd64 ~x86"
SLOT="0"
IUSE="gnome-keyring kde"

RDEPEND="${DEPEND}
	gnome-keyring? ( dev-python/gnome-keyring-python )
	kde? ( kde-base/pykde4 dev-python/PyQt4 )"

S="${WORKDIR}/${MY_P}"
